/**
 * AUTO-GENERATED by scripts/build-ranking-seed.mjs — do not edit by hand.
 * Re-run the script to add channels or refresh IDs.
 *
 * Only IDs, handles, category and country live here. Names, avatars and
 * statistics are fetched live from the YouTube Data API at render time.
 */

import type { RankingSeedChannel } from '@/content/rankings/types';

export const rankingChannels: RankingSeedChannel[] = [
  { id: 'UCX6OQ3DkcsbYNE6H8uQQuVA', handle: 'mrbeast', category: 'entertainment', country: 'US' }, // MrBeast
  { id: 'UCq-Fj5jknLsUf-MWSy4_brA', handle: 'tseries', category: 'music', country: 'IN' }, // T-Series
  { id: 'UCbCmjCuTUZos6Inko4u57UQ', handle: 'cocomelon', category: 'kids', country: 'US' }, // Cocomelon - Nursery Rhymes
  { id: 'UCpEhnqL0y41EpW2TvWAHD7Q', handle: 'setindia', category: 'entertainment', country: 'IN' }, // SET India
  { id: 'UCvlE5gTbOvjiolFlEm-c_Ow', handle: 'vladandniki', category: 'kids', country: 'US' }, // Vlad and Niki
  { id: 'UCbp9MyKCTEww4CxEzc_Tp0Q', handle: 'stokestwins', category: 'entertainment', country: 'US' }, // Stokes Twins
  { id: 'UCk8GzjMOrta8yxDcKfylJYw', handle: 'kidsdianashow', category: 'kids', country: 'US' }, // ✿ Kids Diana Show
  { id: 'UCJplp5SjeGSdVdwsfb9Q7lQ', handle: 'likenastyaofficial', category: 'kids', country: 'US' }, // Like Nastya
  { id: 'UCFFbwnve3yF62-tVXkTyHqg', handle: 'zeemusiccompany', category: 'music', country: 'IN' }, // Zee Music Company
  { id: 'UCJ5v_MCY6GNUBTO8-D3XoAg', handle: 'wwe', category: 'sports', country: 'US' }, // WWE
  { id: 'UCyoXW-Dse7fURq30EWl_CUA', handle: 'goldminestelefilms', category: 'film', country: 'IN' }, // Goldmines
  { id: 'UC-lHJZR3Gqxm24_Vd_AJ5Yw', handle: 'pewdiepie', category: 'gaming', country: 'SE' }, // PewDiePie
  { id: 'UC6-F5tO8uklgE9Zy8IvbdFw', handle: 'sonysab', category: 'entertainment', country: 'IN' }, // Sony SAB
  { id: 'UC5gxP-2QqIh_09djvlm9Xcg', handle: 'alanchikinchow', category: 'entertainment', country: 'US' }, // Alan's Universe
  { id: 'UCOmHUn--16B90oW2L6FRR3A', handle: 'blackpink', category: 'music', country: 'KR' }, // BLACKPINK
  { id: 'UCppHT7SZKKvar4Oc9J4oljQ', handle: 'zeetv', category: 'entertainment', country: 'IN' }, // Zee TV
  { id: 'UCBnZ16ahKA2DZ_T5W0FPUXg', handle: 'chuchutv', category: 'kids', country: 'IN' }, // ChuChu TV Nursery Rhymes & Kids Songs
  { id: 'UCPuEAY09CtdTzFNWuqVZgDw', handle: 'topperguild', category: 'entertainment', country: 'US' }, // Topper Guild
  { id: 'UC2tsySbe9TNrI-xh2lximHA', handle: 'a4a4a4a4', category: 'entertainment', country: 'RU' }, // A4
  { id: 'UCLkAepWjdylmXSltofFvsYQ', handle: 'bts', category: 'music', country: 'KR' }, // BANGTANTV
  { id: 'UCcdwLMPsaU2ezNSJU1nFoBQ', handle: 'pinkfong', category: 'kids', country: 'KR' }, // Baby Shark - Pinkfong Kids’ Songs & Stories
  { id: 'UCtxD0x6AuNNqdXO9Wp5GHew', handle: 'cristiano', category: 'sports', country: 'PT' }, // UR · Cristiano
  { id: 'UCY1kMZp36IQSyNx_9h4mpCg', handle: 'markrober', category: 'education', country: 'US' }, // Mark Rober
  { id: 'UCaayLD9i5x4MmIoVZxXSv_g', handle: 'tseriesbhaktisagar', category: 'music', country: 'IN' }, // T-Series Bhakti Sagar
  { id: 'UCgFXm4TI8htWmCyJ6cVPG_A', handle: 'toysandcolors', category: 'kids', country: 'US' }, // Toys and Colors
  { id: 'UC3IZKseVpdzPSBaWxBxundA', handle: 'hybelabels', category: 'music', country: 'KR' }, // HYBE LABELS
  { id: 'UCJrDMFOdv1I2k8n9oK_V21w', handle: 'tipsofficial', category: 'music', country: 'IN' }, // Tips Official
  { id: 'UC55IWqFLDH1Xp7iu1_xknRA', handle: 'colorstv', category: 'entertainment', country: 'IN' }, // Colors TV
  { id: 'UC295-Dw_tDNtZXFeAPAW6Aw', handle: '5minutecraftsyoutube', category: 'howto', country: 'CY' }, // 5-Minute Crafts
  { id: 'UCyagEfIN1okQ-s996XAqCFQ', handle: 'zhong', category: 'entertainment', country: 'US' }, // Zhong
  { id: 'UCIwFjwMjI0y7PDBVEO9-bkQ', handle: 'justinbieber', category: 'music', country: 'CA' }, // Justin Bieber
  { id: 'UCoQm-PeHC-cbJclKJYJ8LzA', handle: 'fedevigevani', category: 'entertainment', country: 'AR' }, // Fede Vigevani
  { id: 'UCt4t-jeY85JegMlZ-E5UWtA', handle: 'aajtak', category: 'news', country: 'IN' }, // Aaj Tak
  { id: 'UC56gTxNs4f9xZ7Pa2i5xNzg', handle: 'sonymusicindia', category: 'music', country: 'IN' }, // Sony Music India
  { id: 'UCbTLwN10NoCU4WDzLf1JMOA', handle: 'yrf', category: 'music', country: 'IN' }, // YRF
  { id: 'UCK1i2UviaXLUNrZlAFpw_jA', handle: 'elreinoinfantil', category: 'kids', country: 'AR' }, // El Reino Infantil
  { id: 'UC22nIfOTM7KLIQuFGMKzQbg', handle: 'wavemusicindia', category: 'music', country: 'IN' }, // Wave Music
  { id: 'UC4JCksJF76g_MdzPVBJoC3Q', handle: 'arydigitalasia', category: 'entertainment', country: 'PK' }, // ARY Digital HD
  { id: 'UCffDXn7ycAzwL2LDlbyWOTw', handle: 'kondzilla', category: 'music', country: 'BR' }, // Canal KondZilla
  { id: 'UCfM3zsQsOnfWNUppiycmBuw', handle: 'eminem', category: 'music', country: 'US' }, // EminemMusic
  { id: 'UC3gNmTGu-TTbFPpfSs5kNkg', handle: 'movieclips', category: 'film', country: 'US' }, // Movieclips
  { id: 'UC_A7K2dXFsTMAciGmnNxy-Q', handle: 'saregamamusic', category: 'music', country: 'IN' }, // Saregama Music
  { id: 'UCqECaJ8Gagnn7YCbPEzWH6g', handle: 'taylorswift', category: 'music', country: 'US' }, // Taylor Swift
  { id: 'UCRijo3ddMTht_IHyNSNXpNQ', handle: 'dudeperfect', category: 'sports', country: 'US' }, // Dude Perfect
  { id: 'UC4NALVCmcmL5ntpV0thoH6w', handle: 'loolookids', category: 'kids', country: 'US' }, // LooLoo Kids - Nursery Rhymes and Children's Songs
  { id: 'UCF1JIbMUs6uqoZEY1Haw0GQ', handle: 'shemaroo', category: 'film', country: 'IN' }, // Shemaroo
  { id: 'UC4-79UOlP48-QNGgCko5p2g', handle: 'mrbeast2', category: 'entertainment', country: 'US' }, // MrBeast 2
  { id: 'UCWsDFcIhY2DBi3GB5uykGXA', handle: 'ishowspeed', category: 'entertainment', country: 'US' }, // IShowSpeed
  { id: 'UCIPPMRA040LQr5QPyJEbmXA', handle: 'mrbeastgaming', category: 'gaming', country: 'US' }, // MrBeast Gaming
  { id: 'UC0C-w0YjGpqDXGB8IHb662A', handle: 'edsheeran', category: 'music', country: 'GB' }, // Ed Sheeran
  { id: 'UCEdvpU2pFRCVqU6yIPyTpMQ', handle: 'marshmello', category: 'music', country: 'US' }, // Marshmello
  { id: 'UCqJ5zFEED1hWs0KNQCQuYdQ', handle: 'mikecrack', category: 'gaming', country: 'ES' }, // Mikecrack
  { id: 'UCiGm_E4ZwYSHV3bcW1pnSeQ', handle: 'billieeilish', category: 'music', country: 'US' }, // Billie Eilish
  { id: 'UC9CoOnJkIBMdeijd9qYoT_g', handle: 'arianagrande', category: 'music', country: 'US' }, // Ariana Grande
  { id: 'UC-LPIU24bQXVljUXivKEeRQ', handle: 'starplus', category: 'entertainment', country: 'IN' }, // StarPlus
  { id: 'UCYiGq8XF7YQD00x7wAd62Zg', handle: 'juegagerman', category: 'gaming', country: 'CL' }, // JuegaGerman
  { id: 'UCu59yAFE8fM0sVNTipR4edw', handle: 'mashabearen', category: 'kids', country: 'RU' }, // Masha and The Bear
  { id: 'UCstEtN0pgOmCf02EdXsGChw', handle: 'abscbnentertainment', category: 'entertainment', country: 'PH' }, // ABS-CBN Entertainment
  { id: 'UCEeEQxm6qc_qaTE7qTV5aLQ', handle: 'humtv', category: 'entertainment', country: 'PK' }, // HUM TV
  { id: 'UCvh1at6xpV1ytYOAzxmqUsA', handle: 'jessnolimit', category: 'gaming', country: 'ID' }, // Jess No Limit
  { id: 'UCYLNGLIzMhRTi6ZOLjAPSmw', handle: 'shakira', category: 'music', country: 'CO' }, // Shakira
  { id: 'UC_gV70G_Y51LTa3qhu8KiEA', handle: 'luccasneto', category: 'kids', country: 'BR' }, // LUCCAS NETO
  { id: 'UCmBA_wu8xGg1OfOkfW13Q0Q', handle: 'badbunnypr', category: 'music', country: 'PR' }, // Bad Bunny
  { id: 'UCSiDGb0MnHFGjs4E2WKvShw', handle: 'mrindianhacker', category: 'entertainment', country: 'IN' }, // MR. INDIAN HACKER
  { id: 'UCX8pnu3DYUnx8qy8V_c6oHg', handle: 'technogamerzofficial', category: 'gaming', country: 'IN' }, // Techno Gamerz
  { id: 'UCRWFSbif-RFENbBrSiez1DA', handle: 'abpnews', category: 'news', country: 'IN' }, // ABP NEWS
  { id: 'UCttspZesZIDEwwpVIgoZtWQ', handle: 'indiatv', category: 'news', country: 'IN' }, // IndiaTV
  { id: 'UCKe6w0exI94U-RzqAyoY1VA', handle: 'mariaclaraejp', category: 'kids', country: 'BR' }, // Maria Clara & JP
  { id: 'UCV4xOVpbcV8SdueDCOxLXtQ', handle: 'fernanfloo', category: 'gaming', country: 'SV' }, // Fernanfloo
  { id: 'UCOsyDsO5tIt-VZ1iwjdQmew', handle: 'speedrecords', category: 'music', country: 'IN' }, // Speed Records
  { id: 'UC2bYhAHyaqfWlPXWBVk4BcA', handle: 'enaldinho', category: 'gaming', country: 'BR' }, // Enaldinho
  { id: 'UC4hGmH5sABOA70D4fGb8qNQ', handle: 'frostdiamond', category: 'gaming', country: 'ID' }, // Frost Diamond
  { id: 'UCV306eHqgo0LvBf3Mh36AHg', handle: 'felipeneto', category: 'entertainment', country: 'BR' }, // Felipe Neto
  { id: 'UCJrOtniJ0-NWz37R30urifQ', handle: 'alanwalkermusic', category: 'music', country: 'NO' }, // Alan Walker
  { id: 'UCYWOjHweP2V-8kGKmmAmQJQ', handle: 'badabunoficial', category: 'entertainment', country: 'MX' }, // Badabun
  { id: 'UCQZfFRohQ7UX-0CdXl-6pwQ', handle: 'kimberlyloaiza', category: 'entertainment', country: 'MX' }, // Kimberly Loaiza
  { id: 'UCYvmuw-JtVrTZQ-7Y4kd63Q', handle: 'katyperry', category: 'music', country: 'US' }, // Katy Perry
  { id: 'UCj0O6W8yDuLg3iraAXKgCrQ', handle: 'vocesabia', category: 'entertainment', country: 'BR' }, // Você Sabia?
  { id: 'UCLsooMJoIpl_7ux2jvdPB-Q', handle: 'supersimplesongs', category: 'kids', country: 'CA' }, // Super Simple Songs - Kids Songs
  { id: 'UCcgqSM4YEo5vVQpqwN-MaNw', handle: 'rihanna', category: 'music', country: 'US' }, // Rihanna
  { id: 'UCECJDeK0MNapZbpaOzxrUPA', handle: 'luisitocomunica', category: 'entertainment', country: 'MX' }, // Luisito Comunica
  { id: 'UC5c9VlYTSvBSCaoMu_GI6gQ', handle: 'totalgaming093', category: 'gaming', country: 'IN' }, // Total Gaming
  { id: 'UCj22tfcQrWG7EMEKS0qLeEg', handle: 'carryminati', category: 'entertainment', country: 'IN' }, // CarryMinati
  { id: 'UC8f7MkX4MFOOJ2SerXLInCA', handle: 'one31official', category: 'entertainment', country: 'TH' }, // ช่อง one31
  { id: 'UCAOtE1V7Ots4DjM8JLlrYgg', handle: 'peppapigofficial', category: 'kids', country: 'GB' }, // Peppa Pig - Official Channel
  { id: 'UCsT0YIqwnpJCM-mx7-gSA4Q', handle: 'tedx', category: 'education', country: 'US' }, // TEDx Talks
  { id: 'UCZJ7m7EnCNodqnu5SAtg8eQ', handle: 'holasoygerman', category: 'entertainment', country: 'CL' }, // HolaSoyGerman.
  { id: 'UC3KQ5GWANYF8lChqjZpXsQw', handle: 'whindersson', category: 'comedy', country: 'BR' }, // whinderssonnunes
  { id: 'UC4rlAVgAK0SGk-yTfe48Qpw', handle: 'brightsideofficial', category: 'education', country: 'CY' }, // BRIGHT SIDE
  { id: 'UCoUM-UJ7rirJYP8CQ0EIaHA', handle: 'brunomars', category: 'music', country: 'US' }, // Bruno Mars
  { id: 'UC56D-IHcUvLVFTX_8NpQMXg', handle: 'brentrivera', category: 'entertainment', country: 'US' }, // Brent Rivera
  { id: 'UCpYye8D5fFMUPf9nSfgd4bA', handle: 'babybus', category: 'kids', country: 'CN' }, // BabyBus - Preschool Songs & Learning Cartoons
  { id: 'UC3ZkCd7XtUREnjjt3cyY_gg', handle: 'workpointofficial', category: 'entertainment', country: 'TH' }, // WorkpointOfficial
  { id: 'UCq8DICunczvLuJJq414110A', handle: 'zachking', category: 'entertainment', country: 'US' }, // Zach King
  { id: 'UCNUQK9mQoqi4yNXw2_Rj6SA', handle: 'gr6explode', category: 'music', country: 'BR' }, // GR6 EXPLODE
  { id: 'UCIvaYmXn910QMdemBG3v1pQ', handle: 'zeenews', category: 'news', country: 'IN' }, // Zee News
  { id: 'UCSf0s2ogUVYpJPuzW1zpAOg', handle: 'lankybox', category: 'gaming', country: 'US' }, // LankyBox
  { id: 'UCKL5hAuzgFQsyrsQKgU0Qng', handle: 'gmanetwork', category: 'entertainment', country: 'PH' }, // GMA Network
  { id: 'UC9TO_oo4c_LrOiKNaY6aysA', handle: 'daddyyankee', category: 'music', country: 'PR' }, // Daddy Yankee
  { id: 'UCKAqou7V9FAWXpZd9xtOg3Q', handle: 'littlebabybum', category: 'kids', country: 'GB' }, // Little Baby Bum - Nursery Rhymes & Kids Songs
  { id: 'UCZiYbVptd3PVPf4f6eR6UaQ', handle: 'cazetv', category: 'sports', country: 'BR' }, // CazéTV
  { id: 'UCZuPJZ2kGFdlbQu1qotZaHw', handle: 'karolg', category: 'music', country: 'CO' }, // KAROL G
  { id: 'UCEKWXRsfUHkan-D_ljU8Asw', handle: 'rajshri', category: 'film', country: 'IN' }, // Rajshri
  { id: 'UC5OrDvL9DscpcAstz7JnQGA', handle: 'michaeljackson', category: 'music', country: 'US' }, // Michael Jackson
  { id: 'UCXazgXDIYyWH-yXLAkcrFxw', handle: 'elrubiusomg', category: 'gaming', country: 'ES' }, // elrubiusOMG
  { id: 'UChGJGhZ9SOOHvBB0Y4DOO_w', handle: 'ryansworld', category: 'kids', country: 'US' }, // Ryan's World
  { id: 'UC0WP5P-ufpRfjbNrmOWwLBQ', handle: 'theweeknd', category: 'music', country: 'CA' }, // The Weeknd
  { id: 'UCBAb_DK4GYZqZR9MFA7y2Xg', handle: 'galinhapintadinha', category: 'kids', country: 'BR' }, // Galinha Pintadinha
  { id: 'UCjp_3PEaOau_nT_3vnqKIvg', handle: 'junya1gou', category: 'entertainment', country: 'JP' }, // Junya.じゅんや
  { id: 'UC7_YxT-KID8kRbqZo7MyscQ', handle: 'markiplier', category: 'gaming', country: 'US' }, // Markiplier
  { id: 'UCjIA3wwhi0QjSOXAZwOXbPA', handle: 'ozuna', category: 'music', country: 'PR' }, // Ozuna
  { id: 'UCBVjMGOIkavEAhyqpxJ73Dw', handle: 'maroon5', category: 'music', country: 'US' }, // Maroon 5
  { id: 'UCKaCalz5N5ienIbfPzEbYuA', handle: 'jordanmatter', category: 'entertainment', country: 'US' }, // Jordan Matter
  { id: 'UCp0hYYBW6IMayGgR-WeoCvQ', handle: 'theellenshow', category: 'entertainment', country: 'US' }, // TheEllenShow
  { id: 'UCUaT_39o1x6qWjz7K2pWcgw', handle: 'beastreacts', category: 'entertainment', country: 'US' }, // Beast Reacts
  { id: 'UC48h7Dst_hX82HxOf3xJw_w', handle: 'ch3thailand', category: 'entertainment', country: 'TH' }, // Ch3Thailand
  { id: 'UCebC4x5l2-PQxg46Ucv9CsA', handle: 'crazyxyz', category: 'entertainment', country: 'IN' }, // Crazy XYZ
  { id: 'UC-cY4X2sLECUhishGNiyofQ', handle: 'bebefinn', category: 'kids', country: 'KR' }, // Bebefinn - Nursery Rhymes & Kids Songs
  { id: 'UCNApqoVYJbYSrni4YsbXzyQ', handle: 'adityamusic', category: 'music', country: 'IN' }, // Aditya Music
  { id: 'UCt4atlExw8aj3Bm79nv1fig', handle: 'round2hell', category: 'comedy', country: 'IN' }, // Round2hell
  { id: 'UCkAGrHCLFmlK3H2kd6isipg', handle: 'mrbean', category: 'entertainment', country: 'GB' }, // Mr Bean
  { id: 'UCPNxhDvTcytIdvwXWAm43cA', handle: 'selenagomez', category: 'music', country: 'US' }, // Selena Gomez
  { id: 'UCb8vrqP8Z7Oz9ZTYvUtjUHQ', handle: 'daniellabelle', category: 'comedy', country: 'US' }, // Daniel LaBelle
  { id: 'UCt-k6JwNWHMXDBGm9IYHdsg', handle: 'jbalvin', category: 'music', country: 'CO' }, // J Balvin
  { id: 'UCpB959t8iPrxQWj7G6n0ctQ', handle: 'sssniperwolf', category: 'entertainment', country: 'US' }, // SSSniperWolf
  { id: 'UCTkXRDQl0luXxVQrRQvWS6w', handle: 'dream', category: 'gaming', country: 'US' }, // Dream
  { id: 'UCam8T03EOFBsNdR0thrFHdQ', handle: 'vegetta777', category: 'gaming', country: 'ES' }, // VEGETTA777
  { id: 'UCbTVTephX30ZhQF5zwFppBg', handle: 'rezendeevil', category: 'gaming', country: 'BR' }, // rezendeevil
  { id: 'UC_aEa8K-EOJ3D6gOs7HcyNg', handle: 'nocopyrightsounds', category: 'music', country: 'GB' }, // NoCopyrightSounds
  { id: 'UC8-Th83bH_thdKZDJCrn88g', handle: 'fallontonight', category: 'entertainment', country: 'US' }, // The Tonight Show Starring Jimmy Fallon
  { id: 'UCbKWv2x9t6u8yZoB3KcPtnw', handle: 'alanbecker', category: 'entertainment', country: 'US' }, // Alan Becker
  { id: 'UCEf_Bc-KVd7onSeifS3py9g', handle: 'smtown', category: 'music', country: 'KR' }, // SMTOWN
  { id: 'UCWOA1ZGywLbqmigxE4Qlvuw', handle: 'netflix', category: 'film', country: 'US' }, // Netflix
  { id: 'UCsRM0YB_dabtEPGPTKo-gcw', handle: 'adele', category: 'music', country: 'GB' }, // Adele
  { id: 'UCT9zcQNlyht7fRlcjmflRSA', handle: 'imaginedragons', category: 'music', country: 'US' }, // ImagineDragons
  { id: 'UCByOQJjav0CUDwxCk-jVNRQ', handle: 'drakeofficial', category: 'music', country: 'CA' }, // Drake
  { id: 'UCBnxEdpoZwstJqC1yZpOjRA', handle: 'suntv', category: 'entertainment', country: 'IN' }, // Sun TV
  { id: 'UC-CSyyi47VX1lD9zyeABW3w', handle: 'dhruvrathee', category: 'education', country: 'IN' }, // Dhruv Rathee
  { id: 'UC7eHZXheF8nVOfwB2PEslMw', handle: 'ashishchanchlanivines', category: 'comedy', country: 'IN' }, // ashish chanchlani vines
  { id: 'UCxoq-PAQeAdk_zyg8YS0JqA', handle: 'luisfonsi', category: 'music', country: 'PR' }, // Luis Fonsi
  { id: 'UCaO6TYtlC8U5ttz62hTrZgg', handle: 'jypentertainment', category: 'music', country: 'KR' }, // JYP Entertainment
  { id: 'UCpDJl2EmP7Oh90Vylx0dZtA', handle: 'spinninrecords', category: 'music', country: 'NL' }, // Spinnin' Records
  { id: 'UC9ChdqQRCaZmTCwSJ49tcbw', handle: 'sidhumoosewalaofficial', category: 'music', country: 'IN' }, // Sidhu Moose Wala
  { id: 'UCaKLg1ELiX0zTJ6Je3c5esA', handle: 'attahalilintar', category: 'entertainment', country: 'ID' }, // AH
  { id: 'UCYzPXprvl5Y-Sf0g4vX-m6g', handle: 'jacksepticeye', category: 'gaming', country: 'IE' }, // jacksepticeye
  { id: 'UCk3JZr7eS3pg5AGEvBdEvFg', handle: 'villagecookingchannel', category: 'howto', country: 'IN' }, // Village Cooking Channel
  { id: 'UCVp3nfGRxmMadNDuVbJSk8A', handle: 'wizkhalifa', category: 'music', country: 'US' }, // Wiz Khalifa
  { id: 'UCNL1ZadSjHpjm4q9j2sVtOA', handle: 'ladygaga', category: 'music', country: 'US' }, // Lady Gaga
  { id: 'UCAvCL8hyXjSUHKEGuUPr1BA', handle: 'shawnmendes', category: 'music', country: 'CA' }, // Shawn Mendes
  { id: 'UCcYrdFJF7hmPXRNaWdrko4w', handle: 'chrisbrowntv', category: 'music', country: 'US' }, // Chris Brown
  { id: 'UCa10nxShhzNrCE1o2ZOPztg', handle: 'trapnation', category: 'music', country: 'US' }, // Trap Nation
  { id: 'UC3ar28GS6o1p0m_wabfk2zw', handle: 'penmovies', category: 'film', country: 'IN' }, // Pen Movies
  { id: 'UCuHzBCaKmtaLcRAOoazhCPA', handle: 'beyonce', category: 'music', country: 'US' }, // Beyoncé
  { id: 'UCS5Oz6CHmeoF7vSad0qqXfw', handle: 'dantdm', category: 'gaming', country: 'GB' }, // DanTDM
  { id: 'UCyQqzYXQBUWgBTn4pw_fFSQ', handle: 'auronplay', category: 'gaming', country: 'ES' }, // AuronPlay
  { id: 'UCeLHszkByNZtPKcaVXOCOQQ', handle: 'postmalone', category: 'music', country: 'US' }, // Post Malone
  { id: 'UCvrhwpnp2DHYQ1CbXby9ypQ', handle: 'vijaytelevision', category: 'entertainment', country: 'IN' }, // Vijay Television
  { id: 'UCDPM_n1atn2ijUwHd0NNRQw', handle: 'coldplay', category: 'music', country: 'GB' }, // Coldplay
  { id: 'UC3jOd7GUMhpgJRBhiLzuLsg', handle: 'nickiminaj', category: 'music', country: 'US' }, // Nicki Minaj
  { id: 'UCBqFKDipsnzvJdt6UT0lMIg', handle: 'sandeepseminars', category: 'education', country: 'IN' }, // Sandeep Maheshwari
  { id: 'UC1l7wYrva1qCH-wgqcHaaRg', handle: 'davidguetta', category: 'music', country: 'FR' }, // David Guetta
  { id: 'UC24_Z2L-8Ki183AI9zJJzNQ', handle: 'trans7official', category: 'entertainment', country: 'ID' }, // TRANS7 OFFICIAL
  { id: 'UCAuUUnT6oDeKwE6v1NGQxug', handle: 'ted', category: 'education', country: 'US' }, // TED
  { id: 'UC-yXuc1__OzjwpsJPlxYUCQ', handle: 'worldstarhiphop', category: 'music', country: 'US' }, // WORLDSTARHIPHOP
  { id: 'UC_hK9fOxyy_TM8FJGXIyG8Q', handle: 'dharmann', category: 'entertainment', country: 'US' }, // Dhar Mann Studios
  { id: 'UC5PYHgAzJ1wLEidB58SK6Xw', handle: 'blippi', category: 'kids', country: 'US' }, // Blippi - Educational Videos for Kids
  { id: 'UC14UlmYlSNiQCBe9Eookf_A', handle: 'fcbarcelona', category: 'sports', country: 'ES' }, // FC Barcelona
  { id: 'UCs8qka8tfhdc69wzXYdtZ3A', handle: 'lospolinesios', category: 'entertainment', country: 'MX' }, // LosPolinesios
  { id: 'UCOutOIcn_oho8pyVN3Ng-Pg', handle: 'tv9bharatvarsh', category: 'news', country: 'IN' }, // TV9 Bharatvarsh
  { id: 'UCY30JRSgfhYXA6i6xX1erWg', handle: 'smosh', category: 'comedy', country: 'US' }, // Smosh
  { id: 'UCvA9_f5Lwk-poMynabtrZPg', handle: 'ransentertainment', category: 'entertainment', country: 'ID' }, // Rans Entertainment
  { id: 'UCfLuT3JwLx8rvHjHfTymekw', handle: 'triggeredinsaan', category: 'entertainment', country: 'IN' }, // Triggered Insaan
  { id: 'UCpVm7bg6pXKo1Pr6k5kxG9A', handle: 'natgeo', category: 'education', country: 'US' }, // National Geographic
  { id: 'UCqwUrj10mAEsqezcItqvwEw', handle: 'bbkivines', category: 'comedy', country: 'IN' }, // BB Ki Vines
  { id: 'UC-6czyMkxDi8E8akPl0c7_w', handle: 'enriqueiglesias', category: 'music', country: 'ES' }, // Enrique Iglesias
  { id: 'UCG9gfnA5UDoLvz-tC9B-HKw', handle: 'gmmgrammy', category: 'music', country: 'TH' }, // GMM GRAMMY OFFICIAL
  { id: 'UCKqH_9mk1waLgBiL2vT5b9g', handle: 'vanossgaming', category: 'gaming', country: 'CA' }, // VanossGaming
  { id: 'UCC-RHF_77zQdKcA75hr5oTQ', handle: 'fgteev', category: 'gaming', country: 'US' }, // FGTeeV
  { id: 'UCsXVk37bltHxD1rDPwtNM8Q', handle: 'kurzgesagt', category: 'education', country: 'DE' }, // Kurzgesagt – In a Nutshell
  { id: 'UCsTcErHg8oDvUnTzoqsYeNw', handle: 'unboxtherapy', category: 'tech', country: 'CA' }, // Unbox Therapy
  { id: 'UCke6I9N4KfC968-yRcd5YRg', handle: 'ssundee', category: 'gaming', country: 'US' }, // SSundee
  { id: 'UC-J-KZfRV8c13fOCkhXdLiQ', handle: 'dualipa', category: 'music', country: 'GB' }, // Dua Lipa
  { id: 'UCYk4LJI0Pr6RBDWowMm-KUw', handle: 'corbuzier', category: 'entertainment', country: 'ID' }, // Deddy Corbuzier
  { id: 'UCZU9T1ceaOgwfLRq7OKFU4Q', handle: 'linkinpark', category: 'music', country: 'US' }, // Linkin Park
  { id: 'UC9rMiEjNaCSsebs31MRDCRA', handle: 'straykids', category: 'music', country: 'KR' }, // Stray Kids
  { id: 'UCzYfz8uibvnB7Yc1LjePi4g', handle: 'aphmau', category: 'gaming', country: 'US' }, // Aphmau
  { id: 'UCN9HPn2fq-NL8M5_kp4RWZQ', handle: 'sia', category: 'music', country: 'AU' }, // Sia
  { id: 'UC6nSFpj9HTCZ5t-N3Rm3-HA', handle: 'vsauce', category: 'education', country: 'US' }, // Vsauce
  { id: 'UCweOkPb1wVVH0Q0Tlj4a5Pw', handle: '1thek', category: 'music', country: 'KR' }, // 1theK (원더케이)
  { id: 'UCBNs31xysxpAGMheg8OrngA', handle: 'yuya', category: 'entertainment', country: 'MX' }, // Yuya
  { id: 'UCWJ2lWNubArHWmf3FIHbfcQ', handle: 'nba', category: 'sports', country: 'US' }, // NBA
  { id: 'UC_vcKmg67vjMP7ciLnSxSHQ', handle: 'amitbhadana', category: 'comedy', country: 'IN' }, // Amit Bhadana
  { id: 'UCnmGIkw-KdI0W5siakKPKog', handle: 'ryan', category: 'entertainment', country: 'US' }, // Ryan Trahan
  { id: 'UCWwqHwqLSrdWMgp5DZG5Dzg', handle: 'troomtroom', category: 'howto', country: 'CY' }, // Troom Troom
  { id: 'UCucot-Zp428OwkyRm2I7v2Q', handle: 'jamescharles', category: 'entertainment', country: 'US' }, // James Charles
  { id: 'UCOhHO2ICt0ti9KAh-QHvttQ', handle: 'technicalguruji', category: 'tech', country: 'IN' }, // Technical Guruji
  { id: 'UCvC4D8onUfXzvjTOM-dBfEA', handle: 'marvel', category: 'film', country: 'US' }, // Marvel Entertainment
  { id: 'UCG8rbF3g2AMX70yOd8vqIZg', handle: 'loganpaulvlogs', category: 'entertainment', country: 'US' }, // Logan Paul
  { id: 'UCAW-NpUFkMyCNrvRSSGIvDQ', handle: 'ninja', category: 'gaming', country: 'US' }, // Ninja
  { id: 'UCTNtRdBAiZtHP9w7JinzfUg', handle: 'sonymusicsouthvevo', category: 'music', country: 'IN' }, // SonyMusicSouthVEVO
  { id: 'UCDogdKl7t7NHzQ95aEwkdMw', handle: 'sidemen', category: 'entertainment', country: 'GB' }, // Sidemen
  { id: 'UC0DZmkupLYwc0yDsfocLh0A', handle: 'jelly', category: 'gaming', country: 'NL' }, // Jelly
  { id: 'UCwppdrjsBPAZg5_cUwQjfMQ', handle: 'charlieputh', category: 'music', country: 'US' }, // Charlie Puth
  { id: 'UCvgfXK4nTYKudb0rFR6noLA', handle: 'ufc', category: 'sports', country: 'US' }, // UFC
  { id: 'UCq3Ci-h945sbEYXpVlw7rJg', handle: 'thechainsmokers', category: 'music', country: 'US' }, // The Chainsmokers
  { id: 'UCFAiFyGs6oDiF1Nf-rRJpZA', handle: 'technoblade', category: 'gaming', country: 'US' }, // Technoblade
  { id: 'UC1sELGmy5jp5fQUugmuYlXQ', handle: 'minecraft', category: 'gaming', country: 'US' }, // Minecraft
  { id: 'UCMiJRAwDNSNzuYeN2uWa0pA', handle: 'mrwhosetheboss', category: 'tech', country: 'GB' }, // Mrwhosetheboss
  { id: 'UCa6vGFO9ty8v5KZJXQxdhaw', handle: 'jimmykimmellive', category: 'entertainment', country: 'US' }, // Jimmy Kimmel Live
  { id: 'UC5zGJZpxeZPFcds5gFcDE7Q', handle: 'zbingz', category: 'entertainment', country: 'TH' }, // zbing z.
  { id: 'UCIEv3lZ_tNXHzL3ox-_uUGQ', handle: 'gordonramsay', category: 'howto', country: 'GB' }, // Gordon Ramsay
  { id: 'UCPHjpfnnGklkRBBTd0k6aHg', handle: 'avicii', category: 'music', country: 'SE' }, // Avicii
  { id: 'UCU_yU4xGT9hrVFo6euH8LLw', handle: 'slivkishow', category: 'entertainment', country: 'RU' }, // SlivkiShow
  { id: 'UCbW18JZRgko_mOGm5er8Yzg', handle: 'onedirectionvevo', category: 'music', country: 'GB' }, // OneDirectionVEVO
  { id: 'UCHnyfMqiRRG1u-2MsSQLbXA', handle: 'veritasium', category: 'education', country: 'AU' }, // Veritasium
  { id: 'UCBJycsmduvYEL83R_U4JriQ', handle: 'mkbhd', category: 'tech', country: 'US' }, // Marques Brownlee
  { id: 'UCWV3obpZVGgJ3j9FVhEjF2Q', handle: 'realmadrid', category: 'sports', country: 'ES' }, // Real Madrid
  { id: 'UCypeLkg3Ne5-LIyiB41b1GQ', handle: 'ivanaalawi', category: 'entertainment', country: 'PH' }, // Ivana Alawi
  { id: 'UCJFp8uSYCjXOMnkUyb3CQ3Q', handle: 'buzzfeedtasty', category: 'howto', country: 'US' }, // Tasty
  { id: 'UCE_M8A5yxnLfW0KghEeajjw', handle: 'apple', category: 'tech', country: 'US' }, // Apple
  { id: 'UCcgVECVN4OKV6DH1jLkqmcA', handle: 'jakepaul', category: 'entertainment', country: 'US' }, // Jake Paul
  { id: 'UCo8bcnLyZH8tBIH9V1mLgqQ', handle: 'theodd1sout', category: 'entertainment', country: 'US' }, // TheOdd1sOut
  { id: 'UCbt4SegZBQLeXMTMvnrfZtw', handle: 'gatogalactico', category: 'entertainment', country: 'BR' }, // Gato Galactico
  { id: 'UC5BMQOsAB8hKUyHu9KI6yig', handle: 'kbsworldtv', category: 'entertainment', country: 'KR' }, // KBS WORLD TV
  { id: 'UCIPA6iWNaoetaa1T46RkzXw', handle: 'authenticgames', category: 'gaming', country: 'BR' }, // AuthenticGames
  { id: 'UCwIWAbIeu0xI0ReKWOcw3eg', handle: 'unspeakable', category: 'gaming', country: 'US' }, // Unspeakable
  { id: 'UC16niRr50-MSBwiO3YDb3RA', handle: 'bbcnews', category: 'news', country: 'GB' }, // BBC News
  { id: 'UCCEmjNPpJYhGDgaEqeeA4HA', handle: 'thegrefg', category: 'gaming', country: 'ES' }, // TheGrefg
  { id: 'UCupvZG-5ko_eiXAupbDfxWw', handle: 'cnn', category: 'news', country: 'US' }, // CNN
  { id: 'UCZf__ehlCEBPop-_sldpBUQ', handle: 'hikakintv', category: 'entertainment', country: 'JP' }, // HikakinTV
  { id: 'UC4PooiX37Pld1T8J5SYT-SQ', handle: 'goodmythicalmorning', category: 'entertainment', country: 'US' }, // Good Mythical Morning
  { id: 'UCIjYyZxkFucP_W-tmXg_9Ow', handle: 'calvinharris', category: 'music', country: 'GB' }, // Calvin Harris
  { id: 'UCzgxx_DM2Dcb9Y1spb9mUJA', handle: 'twice', category: 'music', country: 'KR' }, // TWICE
  { id: 'UCyps-v4WNjWDnYRKmZ4BUGw', handle: 'airrack', category: 'entertainment', country: 'US' }, // Airrack
  { id: 'UCGmnsW623G1r-Chmo5RB4Yw', handle: 'ksi', category: 'entertainment', country: 'GB' }, // KSI
  { id: 'UCEWHPFNilsT0IfQfutVzsag', handle: 'portadosfundos', category: 'comedy', country: 'BR' }, // Porta dos Fundos
  { id: 'UCiMhD4jzUqG-IgPzUmmytRQ', handle: 'queen', category: 'music', country: 'GB' }, // Queen Official
  { id: 'UCqjjyPUghDSSKFBABM_CXMw', handle: 'anitta', category: 'music', country: 'BR' }, // Anitta
  { id: 'UCkjjH0hsvaeRIuwGlM9oSvg', handle: 'mispastelitos', category: 'entertainment', country: 'MX' }, // Mis Pastelitos
  { id: 'UCNye-wNBqNL5ZzHSJj3l8Bg', handle: 'aljazeeraenglish', category: 'news', country: 'QA' }, // Al Jazeera English
  { id: 'UCv8nzwVPQDRjkPCkEsOdEwA', handle: 'pitbull', category: 'music', country: 'US' }, // Pitbull
  { id: 'UCJZam2u1G0syq3kyqrCXrNw', handle: 'prestonplayz', category: 'gaming', country: 'US' }, // PrestonPlayz
  { id: 'UCpGdL9Sn3Q5YWUH2DVUW1Ug', handle: 'popularmmos', category: 'gaming', country: 'US' }, // PopularMMOs
  { id: 'UCaY_-ksFSQtTGk0y1HA_3YQ', handle: 'ibaillanos', category: 'entertainment', country: 'ES' }, // Ibai
  { id: 'UCqFzWxSCi39LnW1JKFR3efg', handle: 'saturdaynightlive', category: 'entertainment', country: 'US' }, // Saturday Night Live
  { id: 'UC8rNKrqBxJqL9izOOMxBJtw', handle: 'willyrex', category: 'gaming', country: 'ES' }, // Willyrex
  { id: 'UCio_FVgKVgqcHrRiXDpnqbw', handle: 'camilacabello', category: 'music', country: 'US' }, // Camila Cabello
  { id: 'UClkRzsdvg7_RKVhwDwiDZOA', handle: 'jflamusic', category: 'music', country: 'KR' }, // JFlaMusic
  { id: 'UCmh5gdwCx6lN7gEC20leNVA', handle: 'daviddobrik', category: 'entertainment', country: 'US' }, // David Dobrik
  { id: 'UC-2Y8dQb0S6DtpxNgAKoJKA', handle: 'playstation', category: 'gaming', country: 'US' }, // PlayStation
  { id: 'UCX6b17PVsYBQ0ip5gyeme-Q', handle: 'crashcourse', category: 'education', country: 'US' }, // CrashCourse
  { id: 'UCvpDeGlR5wLP9Z3Tb6K0Xfg', handle: 'samsmith', category: 'music', country: 'GB' }, // SAM SMITH
  { id: 'UCXuqSBlHAE6Xw-yeJA0Tunw', handle: 'linustechtips', category: 'tech', country: 'CA' }, // Linus Tech Tips
  { id: 'UCDVYQ4Zhbm3S2dlz7P1GBDg', handle: 'nfl', category: 'sports', country: 'US' }, // NFL
  { id: 'UCy3zgWom-5AGypGX_FVTKpg', handle: 'oliviarodrigo', category: 'music', country: 'US' }, // Olivia Rodrigo
  { id: 'UCIvqWqjC4aLvp7zI8hzARrA', handle: 'littlemix', category: 'music', country: 'GB' }, // Little Mix
  { id: 'UCgMPP6RRjktV7krOfyUewqw', handle: 'hajimesyacho', category: 'entertainment', country: 'JP' }, // はじめしゃちょー（hajime）
  { id: 'UCLysbxhOO_JPOPgcsPCMb8w', handle: 'nianaguerrero', category: 'entertainment', country: 'PH' }, // Niana Guerrero
  { id: 'UCZFWPqqPkFlNwIxcpsLOwew', handle: 'harrystyles', category: 'music', country: 'GB' }, // Harry Styles
  { id: 'UCXIJgqnII2ZOINSWNOGFThA', handle: 'foxnews', category: 'news', country: 'US' }, // Fox News
  { id: 'UCGwu0nbY2wSkW8N-cghnLpA', handle: 'jaidenanimations', category: 'entertainment', country: 'US' }, // JaidenAnimations
  { id: 'UCdAt_KUKt0g9ZRQ7gwKaN3A', handle: 'ranzkyle', category: 'entertainment', country: 'PH' }, // Ranz Kyle
  { id: 'UCgoxyzvouZM-tCgsYzrYtyg', handle: 'nishamadhulika', category: 'howto', country: 'IN' }, // NishaMadhulika
  { id: 'UCfLuMSIDmeWRYpuCQL0OJ6A', handle: 'kwebbelkop', category: 'gaming', country: 'NL' }, // Kwebbelkop
  { id: 'UCChqsCRFePrP2X897iQkyAA', handle: 'kabitaskitchen', category: 'howto', country: 'IN' }, // Kabita's Kitchen
  { id: 'UCiWLfSweyRNmLpgEHekhoAg', handle: 'espn', category: 'sports', country: 'US' }, // ESPN
  { id: 'UC0cGVh96osM7yqMu0ENSKKQ', handle: 'mundobita', category: 'kids', country: 'BR' }, // Mundo Bita
  { id: 'UCiGyWN6DEbnj2alu7iapuKQ', handle: 'physicswallah', category: 'education', country: 'IN' }, // Physics Wallah - Alakh Pandey
  { id: 'UClG8odDC8TS6Zpqk9CGVQiQ', handle: 'fortnite', category: 'gaming', country: 'US' }, // Fortnite
  { id: 'UClfos9f7uDdoun8ZyE9jYFg', handle: 'fukrainsaan', category: 'entertainment', country: 'IN' }, // Fukra Insaan
  { id: 'UC5Ti4_DVp7LW34PjEwB13Xg', handle: 'morphle', category: 'kids', country: 'US' }, // Morphle TV
  { id: 'UCXUJJNoP1QupwsYIWFXmsZg', handle: 'techburner', category: 'tech', country: 'IN' }, // Tech Burner
  { id: 'UCshoKvlZGZ20rVgazZp5vnQ', handle: 'captainsparklez', category: 'gaming', country: 'US' }, // CaptainSparklez
  { id: 'UCWZmCMB7mmKWcXJSIPRhzZw', handle: 'miniminter', category: 'entertainment', country: 'GB' }, // Miniminter
  { id: 'UC_c-RTowPbIlzMkIa_O7s6Q', handle: 'duckybhai', category: 'gaming', country: 'PK' }, // Ducky Bhai
  { id: 'UCG5qGWdu8nIRZqJ_GgDwQ-w', handle: 'premierleague', category: 'sports', country: 'GB' }, // Premier League
  { id: 'UCh5mLn90vUaB1PbRRx_AiaA', handle: 'moresidemen', category: 'entertainment', country: 'GB' }, // MoreSidemen
  { id: 'UCQmZ9BIYOBSkxL-eqqg5z-g', handle: 'markangelcomedy', category: 'comedy', country: 'NG' }, // MarkAngelComedy
  { id: 'UCkzCjdRMrW2vXLx8mvPVLdQ', handle: 'mancity', category: 'sports', country: 'GB' }, // Man City
  { id: 'UC4a-Gbdw7vOaccHmFo40b9g', handle: 'khanacademy', category: 'education', country: 'US' }, // Khan Academy
  { id: 'UCibEhpu5HP45-w7Bq1ZIulw', handle: 'fischers', category: 'entertainment', country: 'JP' }, // Fischer's-フィッシャーズ-
  { id: 'UCoEmptob-eEGKk18c2VplJg', handle: 'kaicenat', category: 'entertainment', country: 'US' }, // Kai Cenat
  { id: 'UCvksjnr7kInzcIjMpJpqF2A', handle: 'littleangel', category: 'kids', country: 'US' }, // Little Angel: Nursery Rhymes & Kids Songs
  { id: 'UCutJqz56653xV2wwSvut_hQ', handle: 'tokaionair', category: 'entertainment', country: 'JP' }, // 東海オンエア
  { id: 'UCey_c7U86mJGz1VJWH5CYPA', handle: 'ijustine', category: 'tech', country: 'US' }, // iJustine
  { id: 'UCqOoboPm3uhY_YXhvhmL-WA', handle: 'discovery', category: 'education', country: 'US' }, // Discovery
  { id: 'UC7krt1E6XvrywJBu0ZOyq3Q', handle: 'khanglobalstudies', category: 'education', country: 'IN' }, // Khan Global Studies
  { id: 'UCAEv0ANkT221wXsTnxFnBsQ', handle: 'tseriestamil', category: 'music', country: 'IN' }, // T-Series Tamil
];
