export type RankingCategory =
  | 'music'
  | 'entertainment'
  | 'kids'
  | 'gaming'
  | 'education'
  | 'howto'
  | 'comedy'
  | 'tech'
  | 'sports'
  | 'film'
  | 'news';

/** One entry in the curated channel pool (generated by scripts/build-ranking-seed.mjs). */
export interface RankingSeedChannel {
  id: string;
  handle: string;
  category: RankingCategory;
  /** ISO 3166-1 alpha-2 country code. */
  country: string;
}
